I have this api see below,

@app.route('/fetch-filter-attributes-v2', methods=['GET'])
def get_filter_attributes_v2() -> ResponseReturnValue:
    """
    Fetch filter options from dynamoDB table - version 2.

    Returns:
        (ResponseReturnValue): filter options list and status code.
    """
    try:
        page = request.args.get('page')
        filter_level = request.args.get('filter_level')
        generation = request.args.get('generation')
        response = filter_attributes_table.get_item(
            Key={'page': page, 'filter_level': filter_level}
        )
        common_attributes = response['Item']['common_attributes']
        gen_attributes = response['Item'][f'gen_attributes_{generation}']
        final_response = {**common_attributes, **gen_attributes}
        logging.info(
            f"dynamoDB response for fetching filter " f"attributes: {response}"
        )
        return (
            jsonify(final_response),  # type: ignore
            200,
        )
    except KeyError as e:
        logging.error("KeyError occurred: %s", str(e))
        return (
            jsonify({'message': "No generation category information found"}),
            404,
        )
    except Exception as e:
        logging.exception(f"An error occurred: {str(e)}")
        return jsonify({"message": str(e)}), 500

I have written test case for keyError see below,

@mock_aws
@pytest.mark.usefixtures("dynamodb_resource")
@patch("main.filter_attributes_table")
def test_get_filter_attributes_v2_keyError(mock_ddb, cloudwatch_log_client, ssm_client, dynamodb_resource):
    """Test fetching filter attributes version 2 keyError."""
    put_parameter_store_config(ssm_client, ENV)

    create_users_table(dynamodb_resource)   
    user_table = dynamodb_resource.Table(USER_TABLE_NAME)
    insert_items_into_users_table(user_table)

    create_cloudwatch_log_group(
        cloudwatch_log_client, CLOUDWATCH_LOG_GROUP_NAME)

    with patch('utility.get_db_client') as mock_db_client:
        mock_db_client.return_value = OS_DB_CLIENT
        from main import app
        app.config['TESTING'] = True
        with app.test_client() as client:
            client.set_cookie("user_id", "100")
            mock_get_item = Mock()
            mock_get_item.return_value = {
                "Item": {
                    key: deserializer.deserialize(value) for key, value in SAMPLE_FILTER_DATA_V2.items()
                }
            }
            mock_ddb.get_item = mock_get_item
            response = client.get('/fetch-filter-attributes-v2',
                                  query_string={'page': "event_sessions",
                                                'filter_level': "L3",
                                                'generation': "1"})


            assert response.status_code == 404
            assert response['message'] == "No generation category information found"

but I am getting this error see below,

FAILED tests/test_main.py::test_get_filter_attributes_v2_keyError - TypeError: 'WrapperTestResponse' object is not subscriptable

can you please fix it? 
