def get_user_email() -> str:
    """
    Retrieve the email associated with current user from AWS Cognito User Pool.

    Returns:
        str: The user email.
    """
    user_id = g.get("user_id")
    user_pool_id = get_user_pool_id()

    if not user_id or not user_pool_id:
        return ""
    try:
        cognito_client = boto3.client('cognito-idp', region_name=REGION_NAME)
        cognito_response = cognito_client.admin_get_user(
            UserPoolId=user_pool_id,
            Username=user_id,
        )
        user_attr = cognito_response['UserAttributes']
        return next(
            (attr["Value"] for attr in user_attr if attr["Name"] == "email"),
            "",
        )
    except ClientError as e:
        logging.error(f"Error fetching user data: {e}")
        return ""

I got this comment on the above function please see below

Please utilize the logging.exception block to log the exception. So, that we can access the exception stack traces.

