def get_user_email() -> str:
    """
    Fetch the email associated with a given user ID from the Cognito User Pool.

    Returns:
        str: The email associated with the user ID or an error message

    Raises:
        IndexError:If the email attribute is not found in the user's attributes
    """
    try:
        user_id = g.user_id if g.get("user_id") else None
        user_pool_id = get_user_pool_id()
        if user_id and user_pool_id:
            cognito_client = boto3.client('cognito-idp', region_name=REGION_NAME)
            cognito_response = cognito_client.admin_get_user(
                UserPoolId=user_pool_id,
                Username=user_id,
            )
            user_attr = cognito_response['UserAttributes']
            email = next((attr["Value"] for attr in user_attr if attr["Name"] == "email"), None)
            return email
        return None
    except NoCredentialsError:
        return "AWS credentials not found."
    except ClientError:
        return "Error fetching user data."
    except IndexError:
        return "Email attribute not found in user's attributes."

for the above utility function do we need to handle this exceptions?
if not required correct the function 
also corretc the docstring and annotations. 
